controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints: [ur_arm_shoulder_pan_joint, ur_arm_shoulder_lift_joint, ur_arm_elbow_joint, ur_arm_wrist_1_joint, ur_arm_wrist_2_joint, ur_arm_wrist_3_joint, ur_arm_ee_joint]
