sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /realsense_d415_arch/depth/image_rect_raw
    queue_size: 1
    near_clipping_plane_distance: 0.4
    far_clipping_plane_distance: 2.0
    shadow_threshold: 0.2
    padding_scale: 4.0
    padding_offset: 0.03
    filtered_cloud_topic: filtered_cloud
